// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webapp.Shared.Data;

#nullable disable

namespace Shared.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240429190817_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Webapp.Shared.Entities.SavingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Savings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 590m,
                            Category = 0,
                            Date = new DateTime(2024, 4, 29, 21, 8, 16, 815, DateTimeKind.Local).AddTicks(9460),
                            Name = "Salary 1"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 640m,
                            Category = 0,
                            Date = new DateTime(2024, 5, 29, 21, 8, 16, 815, DateTimeKind.Local).AddTicks(9510),
                            Name = "Salary 2"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 20.00m,
                            Category = 1,
                            Date = new DateTime(2024, 4, 29, 22, 8, 16, 815, DateTimeKind.Local).AddTicks(9520),
                            Name = "Saving 1"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 35.00m,
                            Category = 1,
                            Date = new DateTime(2024, 5, 30, 21, 8, 16, 815, DateTimeKind.Local).AddTicks(9520),
                            Name = "Saving 2"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 62.00m,
                            Category = 2,
                            Date = new DateTime(2024, 4, 29, 23, 8, 16, 815, DateTimeKind.Local).AddTicks(9530),
                            Name = "Books"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 93.00m,
                            Category = 2,
                            Date = new DateTime(2024, 5, 31, 21, 8, 16, 815, DateTimeKind.Local).AddTicks(9530),
                            Name = "Toys"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
